### ISSUE TITLE
Course 1, Week2, Assignment 6, Logistic Regression with neural network mindset.

### ISSUE THREAD

**Issue by akhilesh-k** [7avenged/deep-learning_coursera#1]
**Week2, Course 1, Assignment 6, Logistic Regression with neural network mindset**<br>

**Issue with arg value**<br>
    `# initialize parameters with zeros `
    `w, b = initialize_with_zeros(3)`
- While initializing the zeros hardcode the dimensions of gradient shape as a constant, instead look for quantities you need with gradient shape for training.

****
Attached error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-db80af875783> in <module>()
----> 1 d = model(train_set_x, train_set_y, test_set_x, test_set_y, num_iterations = 2000, learning_rate = 0.005, print_cost = True)

<ipython-input-27-e94fb9f35524> in model(X_train, Y_train, X_test, Y_test, num_iterations, learning_rate, print_cost)
     24 
     25     # Gradient descent (≈ 1 line of code)
---> 26     parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost = False)
     27 
     28     # Retrieve parameters w and b from dictionary "parameters"

<ipython-input-17-1c4ea7c2e3f4> in optimize(w, b, X, Y, num_iterations, learning_rate, print_cost)
     32         # Cost and gradient calculation (≈ 1-4 lines of code)
     33         ### START CODE HERE ###
---> 34         grads, cost = propagate(w, b, X, Y)
     35         ### END CODE HERE ###
     36 

<ipython-input-15-33eeefeaa8c7> in propagate(w, b, X, Y)
     24     # FORWARD PROPAGATION (FROM X TO COST)
     25     ### START CODE HERE ### (≈ 2 lines of code)
---> 26     z1 = np.dot((w.T),X) + b
     27     A = sigmoid(z1)                                    # compute activation
     28     temp = -(Y*np.log(A)+ ((1-Y)*np.log(1-A)))

ValueError: shapes (1,3) and (12288,209) not aligned: 3 (dim 1) != 12288 (dim 0)

**Comment by Kaushal0709** [comment]
Hi Akhilesh,
Me too facing the same error. Can you please help me to resolve this.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-112-db80af875783> in <module>()
----> 1 d = model(train_set_x, train_set_y, test_set_x, test_set_y, num_iterations = 2000, learning_rate = 0.005, print_cost = True)

<ipython-input-111-90e4c71ff41f> in model(X_train, Y_train, X_test, Y_test, num_iterations, learning_rate, print_cost)
     24 
     25     # Gradient descent (≈ 1 line of code)
---> 26     parameters, grads, costs = optimize(w, b, X, Y, num_iterations,learning_rate, print_cost = False)
     27 
     28     # Retrieve parameters w and b from dictionary "parameters"

<ipython-input-107-d74d2fa02116> in optimize(w, b, X, Y, num_iterations, learning_rate, print_cost)
     32         # Cost and gradient calculation (≈ 1-4 lines of code)
     33         ### START CODE HERE ###
---> 34         grads, cost = propagate(w,b,X,Y)
     35         ### END CODE HERE ###
     36 

<ipython-input-105-21fd7831e4b7> in propagate(w, b, X, Y)
     24     # FORWARD PROPAGATION (FROM X TO COST)
     25     ### START CODE HERE ### (≈ 2 lines of code)
---> 26     A = sigmoid(np.dot(w.T,X)+b)                                   # compute activation
     27     cost = (-1/m) * np.sum(Y*np.log(A)+(1-Y)*np.log(1-A))            # compute cost
     28     #print(A.shape)

ValueError: shapes (1,12288) and (2,3) not aligned: 12288 (dim 1) != 2 (dim 0)

**Comment by hykavitha** [comment]
is this resolved?

**Comment by akhilesh-k** [comment]
I guess no. The user is maybe not managing this repository actively.

**Comment by vijaykumar149** [comment]
> is this resolved?

Yep.

**Comment by songquanpeng** [comment]
In the `model` function, notice this line:
`parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)`

Notice the parameters, it's X_train and Y_train. not X & Y.
I think the reason is u guys just copy the above code and forget to change the parameters.

**Comment by taneemishere** [comment]
In the part where it says initialize the parameters, there you should write it as: 
`w, b = initialize_with_zeros(X_train.shape[0])` 
The error occurs because we write `X.shape[0]` and there in the `model()` we don't have X we have `X_train`.

I hope this will solve the issue! 🕵️‍♀️
